apiVersion: v1
kind: PersistentVolume
metadata:
  name: dgb-volume-{{ .Release.Name }}
  labels:
    type: local
    backupType: {{ .Values.threefoldVdc.backup | quote }}
spec:
  storageClassName: local-path
  capacity:
    storage: 40Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/dgb"
