apiVersion: v1
kind: Service
metadata:
  name: p2p-digibyte-node-{{ .Release.Name }}
  labels:
    {{- include "digibyte.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 12024
      targetPort: 12024
  selector:
    {{- include "digibyte.selectorLabels" . | nindent 4 }}
