apiVersion: v1
kind: Service
metadata:
  name: rpc-digibyte-node-{{ .Release.Name }}
  labels:
    {{- include "digibyte.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 14022
      targetPort: 14022
  selector:
    {{- include "digibyte.selectorLabels" . | nindent 4 }}
