apiVersion: v1
kind: Service
metadata:
  name: "{{ include "zeroci.fullname" . }}-redis"
  labels:
    {{- include "zeroci.labels" . | nindent 4 }}
    backupType: {{ .Values.threefoldVdc.backup | quote }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.redis }}
      protocol: TCP
      name: redis
  selector:
    {{- include "zeroci.selectorLabels" . | nindent 4 }}
