apiVersion: v1
kind: PersistentVolume
metadata:
  name: "{{ include "cryptpad.fullname" . }}-data"
spec:
  capacity:
    storage: "{{ .Values.volume.size }}Gi"
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: ""
  hostPath:
    path: {{ .Values.volume.hostPath }}

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "{{ include "cryptpad.fullname" . }}-data-claim"
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: "{{ .Values.volume.size }}Gi"
  storageClassName: ""
  volumeName: "{{ include "cryptpad.fullname" . }}-data"
