apiVersion: batch/v1beta1
kind: CronJob
metadata:
metadata:
  name: {{ template "name" . }}-maintenance
  labels:
    app: {{ template "name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  schedule: "0 {{ .Values.web.maintenanceHour }} * * *"
  concurrencyPolicy: Replace
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
          - name: {{ template "name" . }}-maintenance
            image: "{{ .Values.web.image }}:{{ .Values.web.imageTag }}"
            imagePullPolicy: {{ .Values.web.imagePullPolicy | quote }}
            command: ["/bin/sh"]
            args:
            - "-c"
            - "tootctl media remove --days={{ .Values.web.keepMediaDays }} && tootctl statuses remove"
            env:
{{ include "productonEnvironment" . | indent 12 }}
            volumeMounts:
            - name: assets
              mountPath: /opt/mastodon/public/assets
          volumes:
          - name: assets
            persistentVolumeClaim:
              claimName: {{ template "web.fullname" . }}-assets
