# Default values for matic.
replicaCount: 1

image:
  repository: arrajput/matic
  pullPolicy: Always
  tag: "latest"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

global:
 ingress:
  enabled: true
# The host should be overrided with the domain name in the chatflow  
  host: "fullnode.matic"
  certresolver: default
  annotations:
    kubernetes.io/ingress.class: traefik
    ingress.kubernetes.io/ssl-passthrough: "true"
  paths: 
    - "/"
  tls: []
 
# Node secrets - These should be set from the chatflow
access_code: ""  
eth_privkey: ""
eth_key_passphrase: ""

# These values should be overrided from the chatflow
env:
    "eth_rpc_url": ""
    "eth_walletaddr": ""
    "sentry_nodeid": ""
    "sentry_enodeid": ""
    "node_type": ""
    "node_ingress_ip": ""

resources: 
    limits:
      cpu: 2000m
      memory: 2024Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

threefoldVdc:
  backup: ''
