apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ template "peertube.fullName" . }}
  labels:
    {{- include "peertube.labels" . | nindent 4 }}
spec:
  rules:
    - host: {{ .Values.webserver.hostname }}
      http:
        paths:
        - path: /
          backend:
            serviceName: {{ template "peertube.fullName" . }}
            servicePort: ing2svc
