{{- if not .Values.deps.smtp.existingSecret -}}
kind: Secret
type: Opaque
apiVersion: v1
metadata:
  name: {{ template "peertube.smtpSecretName" . }}
  labels:
    app: {{ template "peertube.fullName" . }}
    chart: {{ template "peertube.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  un: {{ .Values.deps.smtp.username | b64enc | quote }}
  pw: {{ .Values.deps.smtp.password | b64enc | quote }}
{{- end -}}

