apiVersion: "v1"
name: "peertube"
version: 0.0.1
description: "Federated (ActivityPub) video streaming platform using P2P (BitTorrent) directly in the web browser with WebTorrent."
keywords:
  - "peertube"
  - "video"
  - "streaming"
  - "p2p"
home: "https://joinpeertube.org/"
sources:
  - "https://github.com/Chocobozzz/PeerTube"
maintainers:
  - name: "Amit Kumar Gupta (Original owner)"
    url: "https://akgupta.ca"
icon: "https://joinpeertube.org/favicon.png"
appVersion: "production-stretch"
dependencies:
- name: postgresql
  version: 10.0.0
  repository: https://charts.bitnami.com/bitnami
  condition: deps.pg.managed
- name: redis
  version: 12.0.1
  repository: https://charts.bitnami.com/bitnami
  condition: deps.redis.managed
