apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: dash-ingweb-{{ .Release.Name }}
  labels:
    {{- include "dash.labels" . | nindent 4 }}
    backupType: {{ .Values.threefoldVdc.backup | quote }}
  annotations:
  {{- if .Values.global.ingress.certresolver }}
    traefik.ingress.kubernetes.io/router.tls.certresolver: {{ .Values.global.ingress.certresolver }}
  {{- end }}
  {{- with .Values.global.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  rules:
    - host: {{ .Values.global.ingress.host }}
      http:
        paths:
        - path: /
          backend:
            serviceName: web-dash-node-{{ .Release.Name }}
            servicePort: 80
