{{- if .Values.ingress.enabled -}}
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRouteTCP
metadata:
  name: dash-node-ingress-p2p
spec:
  entryPoints:
    - dash-p2p
  routes:
    - match: HostSNI(`*`)
      services:
        - name: p2p-dash-node
          port: 9999
{{- end }}
