apiVersion: v1
kind: Service
metadata:
  name: {{ include "3bot.fullname" . }}
  labels:
    {{- include "3bot.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      protocol: TCP
      name: https
  selector:
    {{- include "3bot.selectorLabels" . | nindent 4 }}
