{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "tomo.serviceAccountName" . }}
  labels:
    {{- include "tomo.labels" . | nindent 4 }}
    backupType: {{ .Values.threefoldVdc.backup | quote }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
