apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "matic.fullname" . }}
  labels:
    backupType: {{ .Values.threefoldVdc.backup | quote }}
    {{- include "matic.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "matic.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "matic.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "matic.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      volumes:
        - name: matic-storage-{{ .Release.Name }}
          persistentVolumeClaim:
            claimName: matic-volume-claim-{{ .Release.Name }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:          
          {{ range $k, $v := .Values.env }}
            - name: {{ $k | quote }}
              value: {{ $v | quote }}
          {{- end }}
            - name: "ACCESS_CODE"
              valueFrom:
                secretKeyRef:
                  key:  access_code
                  name: {{ .Release.Name }}-auth         
          volumeMounts:
            - name: matic-storage-{{ .Release.Name }}
              mountPath: /matic-data
          ports:
            - name: web{{ .Release.Name }}
              containerPort: 80
              protocol: TCP
            - name: bor{{ .Release.Name }}
              containerPort: 30303
              protocol: TCP
            - name: heim{{ .Release.Name }}
              containerPort: 26656
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
