apiVersion: v1
kind: Service
metadata:
  name: heimdall-matic-{{ .Release.Name }}
  labels:
    {{- include "matic.labels" . | nindent 4 }}
    backupType: {{ .Values.threefoldVdc.backup | quote }}
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 26656
      targetPort: 26656
  selector:
    {{- include "matic.selectorLabels" . | nindent 4 }}
