{{- if .Values.global.ingress.enabled -}}
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRouteTCP
metadata:
  name: ingress-bor-{{ .Release.Name }}
  labels:
    backupType: {{ .Values.threefoldVdc.backup | quote }}
spec:
  entryPoints:
    - matic-bor
  routes:
    - match: HostSNI(`*`)
      services:
        - name: bor-{{ .Release.Name }}
          port: {{ .Values.ports.bor | quote }}
{{- end }}
